* æ/bang.el

Read the blog post: https://blog.almost.education/posts/bang-el

~bang.el~ allows one to [[https://duckduckgo.com/][DuckDuckGo's]] [[https://duckduckgo.com/bang][!Bang]] from the comfort of Emacs.

It adds special support for [[https://www.orgroam.com/][Org-roam]], with the function ~bang-roam~ allowing one to search with the roam node's title, and ~bang-roam-wiki~, which does the same specifically for Wikipedia.

** Installation

~bang.el~ requires that [[https://www.orgroam.com/][org-roam]] also be installed. We are working to make this an optional requirement.

*** Doom Emacs

In ~packages.el~:
#+begin_src elisp
(package! bang :recipe (:host github :repo "EducatedAlmost/bang.el"))
#+end_src

In ~config.el~:
#+begin_src elisp
(require 'bang)
#+end_src

** Usage

All functions can also be called interactively.

#+begin_src elisp
;; Can be called from anywhere:
(bang "w" "Gnosis")
(bang-info)
(bang-find-prefix "")

;; Must be called from inside an Org-roam node:
(bang-roam "ma")
(bang-roam-wiki)
#+end_src

Called without a ~TERM~ argument, most Bangs will take one to the website's homepage.

** Example prefixes

- ~!gh~ :: GitHub repositories
- ~!clj~ :: ClojureDocs
- ~!xiny~ :: Learn X in Y minutes, a introduction to any programming language
- ~!pm~ :: PubMed, biomedical papers
- ~!arx~ :: arXiv, physics papers
- ~!wa~ :: WolframAlpha, computational knowledge engine
- ~!ma~ :: MemoryAlpha, the Star Trek Wiki
- ~!awoiaf~ :: A Wiki of Ice and Fire

For a list of prefixes, see [[https://duckduckgo.com/bang][here]], or call ~bang-find-prefix~ or ~bang-info~.

To suggest a new Bang or correct an existing one: https://duckduckgo.com/newbang

** Changing which browser is used

Internally, the functions all call ~browse-url~. To choose which program is used, one can edit the values of ~browse-url-browser-function~ and ~browse-url-generic-function~ as documented [[https://www.emacswiki.org/emacs/BrowseUrl][here]].
